'use client';
import { useEffect, useMemo, useState } from 'react';
import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

type Options = { outlets: string[]; brands: string[]; groups: string[]; orderTypes: string[]; range: { start: string; end: string }; rows: number; mode: string };
type Data = { metrics: { records: number; orders: number; revenue: number; averageOrder: number; items: number }; charts: { byDay: { date: string; revenue: number }[]; byCategory: { name: string; value: number }[]; byOutlet: { name: string; value: number }[]; bySettlement: { name: string; value: number }[] } };
const palette = ['#7c3aed', '#38bdf8', '#f59e0b', '#f43f5e', '#34d399', '#a78bfa'];
const money = (n: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(n);
const compact = (n: number) => new Intl.NumberFormat('en-IN', { notation: 'compact', maximumFractionDigits: 1 }).format(n);
const Select = ({ label, value, values, onChange }: { label: string; value: string; values: string[]; onChange: (v: string) => void }) => <label><span>{label}</span><select value={value} onChange={e => onChange(e.target.value)}><option value="">All {label.toLowerCase()}s</option>{values.map(v => <option key={v}>{v}</option>)}</select></label>;

export default function Dashboard() {
  const [options, setOptions] = useState<Options | null>(null); const [data, setData] = useState<Data | null>(null); const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState<Record<string, string>>({});
  useEffect(() => { fetch('/api/filters').then(r => r.json()).then((x: Options) => { setOptions(x); setFilter({ start: x.range.start, end: x.range.end }); }).catch(console.error); }, []);
  const query = useMemo(() => new URLSearchParams(Object.entries(filter).filter(([, value]) => value)).toString(), [filter]);
  useEffect(() => { if (!options) return; setLoading(true); fetch(`/api/dashboard?${query}`).then(r => r.json()).then(setData).catch(console.error).finally(() => setLoading(false)); }, [options, query]);
  const update = (key: string) => (value: string) => setFilter(old => ({ ...old, [key]: value }));
  const reset = () => options && setFilter({ start: options.range.start, end: options.range.end });
  if (!options || !data) return <main className="loading"><div className="mark">P</div><p>Preparing your analytics workspace…</p></main>;
  const cards = [['Revenue', money(data.metrics.revenue), 'Gross line-item sales'], ['Orders', compact(data.metrics.orders), 'Unique bills'], ['Average order', money(data.metrics.averageOrder), 'Revenue per bill'], ['Items sold', compact(data.metrics.items), `${compact(data.metrics.records)} line items`]];
  return <main>
    <nav><div className="brand"><b>P</b><span>pulse<span className="dot">.</span></span></div><div className="navmeta"><span className="status"></span>{options.mode} <span className="divider">|</span> {compact(options.rows)} records</div></nav>
    <section className="hero"><div><p className="eyebrow">BUSINESS INTELLIGENCE</p><h1>Sales, in focus.</h1><p className="sub">A real-time view of how your outlets, channels and menu are performing.</p></div><button className="reset" onClick={reset}>↺ Reset filters</button></section>
    <section className="filters" aria-label="Dashboard filters"><label><span>From</span><input type="date" value={filter.start || ''} min={options.range.start} max={filter.end} onChange={e => update('start')(e.target.value)} /></label><label><span>To</span><input type="date" value={filter.end || ''} min={options.range.start} max={options.range.end} onChange={e => update('end')(e.target.value)} /></label><Select label="Outlet" value={filter.outlet || ''} values={options.outlets} onChange={update('outlet')} /><Select label="Brand" value={filter.brand || ''} values={options.brands} onChange={update('brand')} /><Select label="Category" value={filter.group || ''} values={options.groups} onChange={update('group')} /><Select label="Order type" value={filter.orderType || ''} values={options.orderTypes} onChange={update('orderType')} /></section>
    {loading && <div className="progress" />}
    <section className="cards">{cards.map(([label, value, note]) => <article className="metric" key={label}><p>{label}</p><strong>{value}</strong><small>{note}</small></article>)}</section>
    <section className="grid primary"><article className="panel wide"><header><div><h2>Revenue over time</h2><p>Daily gross sales across selected transactions</p></div><strong>{money(data.metrics.revenue)}</strong></header><div className="chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={data.charts.byDay}><CartesianGrid stroke="#ede9fe" vertical={false} /><XAxis dataKey="date" tickFormatter={x => x.slice(5)} minTickGap={30} tick={{ fill: '#8b8795', fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis tickFormatter={x => `₹${compact(x)}`} width={58} tick={{ fill: '#8b8795', fontSize: 11 }} axisLine={false} tickLine={false} /><Tooltip formatter={(v: number) => money(v)} labelFormatter={x => new Date(`${x}T00:00:00`).toLocaleDateString('en-IN', { day: 'numeric', month: 'short' })} /><Line type="monotone" dataKey="revenue" stroke="#7c3aed" strokeWidth={3} dot={false} /></LineChart></ResponsiveContainer></div></article><article className="panel"><header><div><h2>Revenue mix</h2><p>By menu category</p></div></header><div className="chart pie"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data.charts.byCategory} dataKey="value" nameKey="name" innerRadius="55%" outerRadius="80%" paddingAngle={3}>{data.charts.byCategory.map((_, i) => <Cell key={i} fill={palette[i % palette.length]} />)}</Pie><Tooltip formatter={(v: number) => money(v)} /><Legend iconType="circle" iconSize={8} /></PieChart></ResponsiveContainer></div></article></section>
    <section className="grid secondary"><article className="panel"><header><div><h2>Top outlets</h2><p>Revenue contribution</p></div></header><div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart layout="vertical" data={data.charts.byOutlet} margin={{ left: 15 }}><XAxis type="number" hide /><YAxis type="category" dataKey="name" width={100} tick={{ fill: '#56505f', fontSize: 12 }} axisLine={false} tickLine={false} /><Tooltip formatter={(v: number) => money(v)} /><Bar dataKey="value" fill="#38bdf8" radius={[0, 5, 5, 0]} /></BarChart></ResponsiveContainer></div></article><article className="panel"><header><div><h2>Payment channels</h2><p>Revenue by settlement method</p></div></header><div className="channel-list">{data.charts.bySettlement.map((x, i) => <div key={x.name}><span className="swatch" style={{ background: palette[i] }} /><p>{x.name}</p><strong>{money(x.value)}</strong></div>)}</div></article></section>
    <footer>Pulse Analytics · Aggregations are computed server-side; source rows remain off the client.</footer>
  </main>;
}
